In [1]:
# it works on NN arcticture (cbow, skipgram) ----> small data ----> cbow, large data -----> skipgram
# It capture the sementic meaning
# low dimension of collection
# computation time is low
# dense vector
# over fitting problem not occure in this

In [8]:
import gensim
from gensim.models import word2vec, keyedvectors

In [5]:
model = keyedvectors.load_word2vec_format('GoogleNews-vectors-negative300.bin', binary=True)

In [13]:
model['cricket']

array([-3.67187500e-01, -1.21582031e-01,  2.85156250e-01,  8.15429688e-02,
        3.19824219e-02, -3.19824219e-02,  1.34765625e-01, -2.73437500e-01,
        9.46044922e-03, -1.07421875e-01,  2.48046875e-01, -6.05468750e-01,
        5.02929688e-02,  2.98828125e-01,  9.57031250e-02,  1.39648438e-01,
       -5.41992188e-02,  2.91015625e-01,  2.85156250e-01,  1.51367188e-01,
       -2.89062500e-01, -3.46679688e-02,  1.81884766e-02, -3.92578125e-01,
        2.46093750e-01,  2.51953125e-01, -9.86328125e-02,  3.22265625e-01,
        4.49218750e-01, -1.36718750e-01, -2.34375000e-01,  4.12597656e-02,
       -2.15820312e-01,  1.69921875e-01,  2.56347656e-02,  1.50146484e-02,
       -3.75976562e-02,  6.95800781e-03,  4.00390625e-01,  2.09960938e-01,
        1.17675781e-01, -4.19921875e-02,  2.34375000e-01,  2.03125000e-01,
       -1.86523438e-01, -2.46093750e-01,  3.12500000e-01, -2.59765625e-01,
       -1.06933594e-01,  1.04003906e-01, -1.79687500e-01,  5.71289062e-02,
       -7.41577148e-03, -

In [20]:
model.most_similar('man')

[('woman', 0.7664012908935547),
 ('boy', 0.6824870705604553),
 ('teenager', 0.6586930155754089),
 ('teenage_girl', 0.6147903203964233),
 ('girl', 0.5921714305877686),
 ('suspected_purse_snatcher', 0.5716364979743958),
 ('robber', 0.5585118532180786),
 ('Robbery_suspect', 0.5584409832954407),
 ('teen_ager', 0.5549196004867554),
 ('men', 0.5489763021469116)]

In [21]:
model.similarity('man','woman')

0.76640123

In [23]:
model.similarity('man','php')

0.008337107

In [24]:
model.doesnt_match(['PHP','Python','sumit'])

'sumit'

In [27]:
vec = model['king'] - model['man'] + model['queen']

In [28]:
model.most_similar([vec])

[('queen', 0.8422121405601501),
 ('king', 0.8070623278617859),
 ('queens', 0.6293326020240784),
 ('monarch', 0.6233264803886414),
 ('kings', 0.5990484356880188),
 ('princess', 0.5685815215110779),
 ('royal', 0.55137038230896),
 ('princes', 0.5398682951927185),
 ('NYC_anglophiles_aflutter', 0.5370354652404785),
 ('Queen_Consort', 0.5246095061302185)]

# Training your own model

In [1]:
import numpy as np
import pandas as pd
import gensim
import os
import nltk

In [2]:
nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to
[nltk_data]    |     /Users/sumitkumar/nltk_data...
[nltk_data]    |   Package abc is already up-to-date!
[nltk_data]    | Downloading package alpino to
[nltk_data]    |     /Users/sumitkumar/nltk_data...
[nltk_data]    |   Package alpino is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /Users/sumitkumar/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_eng to
[nltk_data]    |     /Users/sumitkumar/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_eng is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /Users/sumitkumar/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_ru is alread

True

In [48]:
from nltk.corpus import stopwords

# stopwords.words('english')

In [49]:
import nltk
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

story = []

for filename in os.listdir('data'):
    file_path = os.path.join('data', filename)

    try:
        # Try to open the file with a more tolerant encoding
        with open(file_path, 'r', encoding='ISO-8859-1') as f:
            corpus = f.read()

        # Removing stopwords
        stop_words_set = set(stopwords.words('english'))  # Using a set for faster lookups
        new_text = [word for word in corpus.split() if word.lower() not in stop_words_set]
        corpus = " ".join(new_text)   

        # Tokenize into sentences and preprocess each one
        raw_sentences = sent_tokenize(corpus)
        for sentence in raw_sentences:
            story.append(simple_preprocess(sentence))

    except UnicodeDecodeError as e:
        print(f"Error reading {filename}: {e}")

In [50]:
story

[['george',
  'martin',
  'dance',
  'dragons',
  'book',
  'five',
  'song',
  'ice',
  'fire',
  'dedication',
  'one',
  'fans',
  'lodey',
  'trebla',
  'stego',
  'pod',
  'caress',
  'yags',
  'ray',
  'mr',
  'kate',
  'chataya',
  'mormont',
  'mich',
  'jamie',
  'vanessa',
  'ro',
  'stubby',
  'louise',
  'agravaine',
  'wert',
  'malt',
  'jo',
  'mouse',
  'telisiane',
  'blackfyre',
  'bronn',
  'stone',
  'coyote',
  'daughter',
  'rest',
  'madmen',
  'wild',
  'women',
  'brotherhood',
  'without',
  'banners',
  'website',
  'wizards',
  'elio',
  'linda',
  'lords',
  'westeros',
  'winter',
  'fabio',
  'wic',
  'gibbs',
  'dragonstone',
  'started',
  'men',
  'women',
  'asshai',
  'spain',
  'sang',
  'us',
  'bear',
  'maiden',
  'fair',
  'fabulous',
  'fans',
  'italy',
  'gave',
  'much',
  'wine',
  'readers',
  'finland',
  'germany',
  'brazil',
  'portugal',
  'france',
  'netherlands',
  'distant',
  'lands',
  'you',
  've',
  'waiting',
  'dance',
  'f

In [51]:
len(story)

144808

In [52]:
from gensim.models import Word2Vec

# Initialize the Word2Vec model with the correct parameters
model = Word2Vec(
    # sentences=story,  # List of tokenized sentences
    window=10,             # Context window size
    min_count=2
)



In [53]:
model.build_vocab(story)

In [54]:
model.train(story,total_examples=model.corpus_count, epochs=model.epochs)

(4798991, 5001035)

In [55]:
model.wv.most_similar('daenerys')

[('stormborn', 0.8984684944152832),
 ('unburnt', 0.8469971418380737),
 ('queen', 0.8300524353981018),
 ('myrcella', 0.8282209634780884),
 ('targaryen', 0.8230838179588318),
 ('elia', 0.8110476732254028),
 ('viserys', 0.8064426779747009),
 ('loraq', 0.8044511675834656),
 ('court', 0.7970327734947205),
 ('dorne', 0.7964118719100952)]

In [56]:
model.wv.similarity('arya','sansa')

0.81089205

In [57]:
model.wv.similarity('arya','tywin')

0.09821151

In [58]:
model.wv.get_normed_vectors()

array([[-0.05307387, -0.06053196,  0.0237551 , ..., -0.17115465,
         0.09436142, -0.03285459],
       [-0.03512672,  0.02912345,  0.12715743, ..., -0.15959959,
        -0.03571011,  0.10680823],
       [ 0.15127096,  0.10766611, -0.03375448, ...,  0.0941397 ,
         0.01080048, -0.04050716],
       ...,
       [ 0.0960955 , -0.01189412, -0.0355417 , ..., -0.09876837,
         0.07997157,  0.00390312],
       [-0.04754916,  0.13177624,  0.09519309, ..., -0.16417658,
         0.09383687,  0.18641241],
       [-0.09143779,  0.08337005, -0.01305173, ..., -0.15483929,
         0.00069844,  0.0813204 ]], dtype=float32)

In [59]:
model.wv.get_normed_vectors().shape

(17451, 100)

In [60]:
y = model.wv.index_to_key

In [61]:
y

['said',
 'lord',
 'would',
 'one',
 'you',
 'ser',
 'him',
 'could',
 'man',
 'it',
 'king',
 'men',
 'back',
 'well',
 'her',
 'like',
 'jon',
 'me',
 'them',
 'he',
 'that',
 'father',
 'the',
 'old',
 'hand',
 'even',
 'tyrion',
 'never',
 'see',
 'know',
 'made',
 'eyes',
 'black',
 'told',
 'lady',
 'thought',
 'time',
 'long',
 'might',
 'us',
 'come',
 'face',
 'still',
 'head',
 'red',
 'way',
 'boy',
 'page',
 'must',
 'queen',
 'good',
 'two',
 'brother',
 'night',
 'little',
 'took',
 'came',
 'll',
 'though',
 'say',
 'three',
 'away',
 'dead',
 'son',
 'no',
 'there',
 'blood',
 'take',
 'go',
 'half',
 'make',
 'and',
 'arya',
 'saw',
 'we',
 'day',
 'white',
 'now',
 'jaime',
 'first',
 'look',
 'want',
 'much',
 'enough',
 'sword',
 'tell',
 'girl',
 'bran',
 'great',
 'looked',
 'again',
 'left',
 'knew',
 'asked',
 'gave',
 'maester',
 'called',
 'wall',
 'every',
 'heard',
 'sansa',
 'let',
 'yet',
 'went',
 'turned',
 'dany',
 'behind',
 'need',
 'around',
 'here',

In [62]:
len(y)

17451

In [63]:
from sklearn.decomposition import PCA

In [64]:
pca = PCA(n_components=3)

In [65]:
X = pca.fit_transform(model.wv.get_normed_vectors())

In [66]:
X[:5]

array([[-0.4421456 ,  0.06048344,  0.2168067 ],
       [-0.38680655,  0.5975077 ,  0.2896715 ],
       [-0.48148748, -0.03069068, -0.22504695],
       [-0.02717981,  0.18737677,  0.01987379],
       [-0.58419406, -0.16312674,  0.1074397 ]], dtype=float32)

In [67]:
X.shape

(17451, 3)

In [71]:
!pip install plotly
!pip install nbformat --upgrade  # Restart the kernal and re-run all

In [72]:
import plotly.express as px

fig = px.scatter_3d(X[:500],x=0,y=1,z=2, color=y[:500])
fig.show()